name: Full Deploy Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy_app:
    uses: ./.github/workflows/deploy-app.yaml
    secrets: inherit
    with:
      aws_access_key_id: ${{ github.secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ github.secrets.AWS_SECRET_ACCESS_KEY }}
      aws_region: ${{ github.secrets.AWS_REGION }}
      aws_account_id: ${{ github.secrets.AWS_ACCOUNT_ID }}
      ecr_repository: ${{ githubsecrets.ECR_REPOSITORY }}
      cluster_name: clusteyyufg
      deployment_file: deployment.yaml
      ingress_file: ingress.yaml

  deploy_monitoring:
    needs: deploy_app
    uses: ./.github/workflows/deploy-monitoring.yaml
    secrets: inherit
    with:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws_region: ${{ secrets.AWS_REGION }}
      aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
      cluster_name: clusteyyufg
